services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p $$POSTGRES_PORT"]
      interval: 10s
      retries: 5
      start_period: 1s
      timeout: 5s
    env_file:
      ./auth-service/configs/postgres.env